Import-Module ActiveDirectory

# Path to the CSV generated by the previous script
$csvPath = Join-Path $PWD "AD_EnabledUsers_InheritanceDisabled.csv"

# Optional: output report of what was changed
$outCsv  = Join-Path $PWD "AD_EnabledUsers_InheritanceEnabled_Result.csv"

$rows = Import-Csv $csvPath

$result = foreach ($r in $rows) {

    # Adjust if your CSV column name differs
    $dn = $r.DistinguishedName

    if ([string]::IsNullOrWhiteSpace($dn)) { continue }

    try {
        $path = "AD:\$dn"
        $acl  = Get-Acl -Path $path

        # Only change those that are actually protected (inheritance disabled)
        if ($acl.AreAccessRulesProtected) {

            # Enable inheritance: disable protection.
            # Second parameter $true keeps existing inherited rules in place.
            $acl.SetAccessRuleProtection($false, $true)

            Set-Acl -Path $path -AclObject $acl

            [pscustomobject]@{
                SamAccountName    = $r.SamAccountName
                DistinguishedName = $dn
                Changed           = $true
                Error             = $null
            }
        }
        else {
            [pscustomobject]@{
                SamAccountName    = $r.SamAccountName
                DistinguishedName = $dn
                Changed           = $false
                Error             = $null
            }
        }
    }
    catch {
        [pscustomobject]@{
            SamAccountName    = $r.SamAccountName
            DistinguishedName = $dn
            Changed           = $null
            Error             = $_.Exception.Message
        }
    }
}

$result | Export-Csv -NoTypeInformation -Encoding UTF8 -Path $outCsv
"Done. Results saved to: $outCsv"